### ISSUE TITLE
Couchbase 4 erlang and goxdcr process taking 99% of the CPU

### ISSUE THREAD

**Issue by victorarbuesmallada** [couchbase/goxdcr#2]
First of all, I understand that Couchbase 4 is not released yet so I'm assuming this is something expected. I'm really pleased with Couchbase so far and it's my first choice of NoSql DB. Also, I'm not sure if this is the proper place to create the issue, please let me know if I'm wrong.

Anyway, we got 3 servers part of a couchbase cluster, same specs (AMD Opteron Processor 6380 2.50 Ghz 16 GB RAM) and in all of them couchbase related processes are taking pretty much all the processing power of the machines.
This cause me troubles for instance if I want to use the couchbase web client to set new replications (it basically crash in that page).

To be said, we got 10 buckets and most of them are replicating against elasticsearch, just in case that makes a difference. Although, this was working fine in previous couchbase versions.

**Comment by ceejatec** [comment]
I'll make sure one of our support reps takes a look at this; thanks for the report.

Can you let us know what specific version of Couchbase you're running - ideally the build number (eg., 4.0.0-1604) from the Console. Also, what platform you are running on.

**Comment by victorarbuesmallada** [comment]
4.0.0-4047 and windows

**Comment by ceejatec** [comment]
Our support avenue is through our Jira: https://issues.couchbase.com/

If you could, please file a ticket there. If you don't have a Couchbase account for the forums, Jira, etc, you should be able to create one here: https://www.couchbase.com/communities/user/register

Thanks!

**Comment by victorarbuesmallada** [comment]
Done
https://issues.couchbase.com/browse/MB-16365

**Comment by ceejatec** [comment]
Thanks again! Closing this issue; any further action will be in Jira.
