### ISSUE TITLE
Getting GOXDCR EOF error when replication starts 

### ISSUE THREAD

**Issue by FurkanInciroglu** [couchbase/goxdcr#7]
Hello there,

curl -v -X POST -u Administrator:password \
http://127.0.0.1:8091/controller/createReplication \
-d fromBucket=source \
-d toCluster=remoteclusterIP \
-d toBucket=remote \
-d replicationType=continuous \
-d compressionType="None"

I am trying to replicate my buckets via POST request. It turned to me HTTP 200 ok and replication id but replication didn't start because of these errors.

"ERRO GOXDCR.CheckpointMgr: err from select bucket for bucket-name" and
"GOXDCR.CheckpointMgr: Failed to construct memcached client for blabla.couchbase.svc:11210, err=EOF"

Do you have any idea to solve this problem?

**Comment by nelio2k** [comment]
Hi @FurkanInciroglu ... can you please open up a discussion topic at https://forums.couchbase.com/? Thanks.
