### ISSUE TITLE
Lack dependent Library "github.com/couchbase/eventing-ee"

### ISSUE THREAD

**Issue by bugwz** [couchbase/goxdcr#9]
# Env
+ Go：1.17.3
+ OS：MacOS
+ goxdcr branch：master
+ goxdcr commit：a886acc36860d2a75fa2b2089543d20d39aa1898

# Problem

When I tried to use `go mod tidy` locally, there were some errors：

```bash
go: finding module for package github.com/couchbase/eventing-ee/evaluator/api
go: finding module for package github.com/couchbase/eventing-ee/evaluator/client
github.com/couchbase/goxdcr/service_impl imports
	github.com/couchbase/eventing-ee/evaluator/api: cannot find module providing package github.com/couchbase/eventing-ee/evaluator/api: module github.com/couchbase/eventing-ee/evaluator/api: git ls-remote -q origin in /Users/guwenzhuang/go/pkg/mod/cache/vcs/9dbe21eb437a8c86b4bc27bf1d46f70160404906e6df371269ddc4cc05203cce: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
github.com/couchbase/goxdcr/service_impl imports
	github.com/couchbase/eventing-ee/evaluator/client: cannot find module providing package github.com/couchbase/eventing-ee/evaluator/client: module github.com/couchbase/eventing-ee/evaluator/client: git ls-remote -q origin in /Users/guwenzhuang/go/pkg/mod/cache/vcs/9dbe21eb437a8c86b4bc27bf1d46f70160404906e6df371269ddc4cc05203cce: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

Is the dependency library private? Enterprise Edition？ Is there any other way I can replace the dependency? I look forward to receiving your reply～

@nelio2k

**Comment by ceejatec** [comment]
Yes, eventing-ee is a private repository. It is only required to build the Enterprise version of goxdcr, but unfortunately the Go Modules mechanism doesn't distinguish dependent modules based on whether they're used or not; it requires the `go.mod` file to fully enumerate all modules it might possibly depend on.

It can be sort of worked around by creating a skeleton directory structure that looks like this in whatever directory your go.mod file is in:

```
empty/
    go.mod
    evaluator/
        api/
            foo.go
        client/
            foo.go
```

where go.mod and both foo.go files are empty (0-byte) files. Then run the command

```
go mod edit -replace github.com/couchbase/eventing-ee=./empty
```

I also had to delete the files `goxdcr/gen_server/gen_server_test.go` and `goxdcr/interface_test/*.go` as they import a non-existing package `github.com/couchbase/couchbase_goxdcr`. Basically, goxdcr is NOT yet a Go Module, so it isn't yet designed to be built as one. But with those changes, `go mod tidy` should work.

It still won't necessarily be possible to compile it, though, as it has CGo dependencies on (at least) sigar.

**Comment by bugwz** [comment]
@ceejatec Thank you for your reply~ I'll try it according to your opinion, Also, I do encounter the problem of sigar dependency. I wonder if this problem can be solved under Mac?（I'm stuck here right now）

**Comment by ceejatec** [comment]
We do build Couchbase Server for MacOS, yes, which includes goxdcr and sigar. Sigar is a C++ library at https://github.com/couchbase/sigar , but much like goxdcr, it's really only set up to be built as part of Couchbase Server... it in turn depends on Boost, jemalloc, libevent, and more, all of which are normally downloaded and configured as part of the Couchbase Server build.

You'll probably have better luck just building Couchbase Server; at least then you're not swimming uphill. It should only take about 15 minutes. If you have Xcode configured for building C++ programs from the command line, it should hopefully be as easy as

```
curl https://storage.googleapis.com/git-repo-downloads/repo -o ~/bin/repo
chmod 755 ~/bin/repo
brew install cmake
mkdir ~/cbsrc
cd ~/cbsrc
repo init -u https://github.com/couchbase/manifest -m couchbase-server/neo.xml
repo sync --jobs=8
make -j8
```

(The first couple lines assume that `~/bin` exists and is on your PATH - just make sure you download the `repo` tool somewhere that is.) After that's done, you should have an `install/bin/goxdcr` binary, along with dependent libraries like sigar in `install/lib`.

Note that I don't have a Mac myself so I can't help much with any further problems you have - you might try searching around or posting on the Couchbase Forums at https://forums.couchbase.com/ . Hope you can get done what you need!
